### ISSUE TITLE
Override Release/Version on CLI

### ISSUE THREAD

**Issue by Dekken** [genereese/togo#19]
Hey, is this possible? It's an function that would be quite useful.

Thanks

**Comment by genereese** [comment]
I like this idea, but I need to figure out how I could best implement it without breaking existing Togo projects.

I'll work on it and see if I can come up with something.

**Comment by Dekken** [comment]
My suggestion would be to allow it on the command

togo build package

i.e.
togo build package -r "1.0" -v "001"

We have our own headers which we use to overwrite the togo generated ones, and so having it on the "togo project create" doesn't make a lot of sense to me.

**Comment by genereese** [comment]
I definitely get what you're suggesting, and I like it. The problem is that this might be beyond the scope of what Togo was designed to do.

Basically, Togo is meant to be a lightweight wrapper around the existing RPM building process. The point of Togo is to add some organization to an extremely loose architecture that has very little documentation as to standardized practices.

In regards to the version and release information (something which is defined in the spec file before building the RPM), Togo attempts to break up the standard spec file into a more readable/usable format, and then simply re-compiles the broken up parts into a single file before building. These parts are generated when the Togo project is created, and are, otherwise, only altered by the user from that point on. Adding this functionality would break that trend.

Though I do like the idea from a sense of automation, I need to figure out a way to best implement the idea without straying too far from the original premise of Togo.

**Comment by genereese** [comment]
I modified Togo to accept version and release information via the command line, but the implementation is incredibly hacky feeling.

Basically, I'm running 'sed' against the generated spec file before the package building process in order to modify the version and release lines. However, that adds another dependency to Togo (sed and related sub-dependencies) and, as I said before, is pretty hacky (and probably subject to a lot of errors).

I think, the best way for you guys to implement this to ensure Togo remains clean is to basically perform that process as part of your deployment script (which I'm assuming is running Togo).

Again, this may be subject to errors, so use it at your own risk, but it is effectively what I was doing in Togo to achieve what you were looking for. So, instead of running:

`togo build package`

-run:

`togo build spec`
`sed -i -- 's/^Version:.*/Version: 3.5/' generated.spec`
`togo build package -s generated.spec`

-where '3.5' is whatever version number you'd like. You may do the same for the 'Release' line as well.

I think this is the best solution for the time being unless I can figure out a way to better implement it while staying true to the core RPM build process.

**Comment by genereese** [comment]
You know... on closer inspection, I realized that I already have a function in Togo that uses sed; I've just never added it as a requirement for the package. I have a section that uses it to rename the current project to something new.

I'm going to leave this issue open and see if I can come up with a more graceful way of tackling both situations.

**Comment by genereese** [comment]
Ok, latest release now supports version and release flags on the build command.

Examples:
`togo build package -v 2.1.2 -r 3`
`togo build package --version 5.2 --release 1`

**Comment by Dekken** [comment]
Neat, I'll check it out.
Thanks.
