### ISSUE TITLE
Add File Flag: %config(noreplace)

### ISSUE THREAD

**Issue by liedekef** [genereese/togo#28]
This is a great script!
Could you support the config-noreplace option as a file flag too?
See http://people.ds.cam.ac.uk/jw35/docs/rpm_config.html

Based on what your script currently already does for config files, I guess it is not that difficult to add (but I'm no python guy).

**Comment by genereese** [comment]
Glad it's helping and thanks for your suggestion. It's not too difficult to add, but I need to clean up a bit of the file database configuration so that the new addition won't hurt existing Togo users/projects.

In short, the flag needs to be added to the file flag table in the database. This currently only happens if you re-initialize the file database using:

`togo file database --init`

While that will re-initialize the file database (and the associated flag types available in the table), it will also reset the project's files to their default flags and the user would need to go re-flag all his/her files.

I intend to perform these changes (along with the addition of file user support) this weekend, so I hope to have the next release ready next week.

**Comment by liedekef** [comment]
Sorry to bug you about this, but did by any chance you make progress on this? If you want, I can test here.

**Comment by genereese** [comment]
Just a heads up that I completed the work on this addition. Please let me know if you encounter any issues with the change. Check:

`# togo file flag`

-for more details.

**Comment by liedekef** [comment]
Much appreciated! I'll give it a swirl later today. Now the file user support and I'm good to go :-)
